### PR TITLE
feat: use gooey from MawGooey module

### PR DESCRIPTION
**Pull request by jdrueckert**
- Gooeys are moved into MawGooey module, use gltf model, skin and textures of green gooey for gooey citizen from there
- gameplay specific assets like skins and textures for market citizen stay

Depends on https://github.com/Terasology/MawGooey/pull/5

### CODE REVIEW

**Comment by pollend** [comment]
what is the status on this? @jdrueckert

**Comment by jdrueckert** [comment]
> what is the status on this? @jdrueckert 

Still working on it but was busy with joml reviews and migrations and investigating Playtest findings this week.
I think I'll get it to a reviewable point tomorrow.

**Review by skaldarnar — CHANGES_REQUESTED** [review]
The white Shopkeeper Gooey is visible and moving as expected.

The MawGooey is moving backwards, though.

image

**Comment by jdrueckert** [comment]
I think both the mawgooey walking sideway and the world gen issues are independent of the gooey asset merger.

**Review by skaldarnar — APPROVED** [review]

**Pull request merged**
