### PR TITLE
Added good and bad robots assets

### PR DESCRIPTION
**Pull request by casals**
### Contains
- Assets for Good Robot and Bad Robot, created by @quaternius

### Objective
Include new assets creating during GSoC 2019

### Changes

- Added new prefabs: `robot_good_animated` and `robot_bad_animated`
- Added correspondent textures and materials

### Usage

In the console (F1), type `spawnPrefab` followed by one of the new prefabs:

- `spawnPrefab robot_good_animated`
- `spawnPrefab robot_bad_animated`

### CODE REVIEW

**Comment by mayant15** [comment]
I had a problem with the bad robot. Is this a known issue? The good robot works great though! 👍 

bad_robot

**Comment by casals** [comment]
Yes - it's a known issue. We discussed this in Discord a while ago but I forgot to actually open the issue, sorry. @Cervator should we merge + open issue or just block the PR for now?

**Comment by AndyTechGuy** [comment]
Just tested this now! I personally think it's important to fix the animation problem before this PR is merged

**Comment by skaldarnar** [comment]
Closing it so we can add the new animation format after MovingBlocks/Terasology#3785 is merged.

**Pull request closed without merging**
